%YAML 1.2
---

distribution_name: 'Shani OS'

internet_connection_required: no

internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

fixed_language: en

suggested_languages:
    - 'en'

welcome_page:
    logo    : '/usr/share/pixmaps/shanios-logo.png'
    text    : '# Welcome to Shani OS!

      **An Immutable OS for Ultimate Reliability**

      This installer will guide you through a quick and secure setup.

      Let's begin!'
    usage   : yes

minimum_disk_size: 64

offer_disk_encryption: yes

# gnome-initial-setup can handle user and locale setup.
# These settings allow to disable these pages.
#
# Default: skip_user: no, skip_locale: no

skip_user: yes
skip_locale: yes

failure_help_url: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'

browser_cmd: 'firefox'
disks_cmd  : 'gnome-disks'
wifi_cmd   : 'gnome-control-center wifi'
