%YAML 1.2
---

distribution_name: 'Shani OS'

internet_connection_required: no

internet_checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'

fixed_language: en

suggested_languages:
    - 'en'

welcome_page:
    logo: '/usr/share/pixmaps/shanios-logo.png'
    text: |
      Welcome to Shani OS!

      An Immutable OS for Ultimate Reliability

      This installer will guide you through a quick and secure setup.

      Let's begin!
    usage: yes
# Minimum disk size needed for the installation (in Gigabyte)
# Default: 5
minimum_disk_size: 28  # Accounts for actual usable space on 32GB cards

# Disk encryption PIN setup.
#
# offered      Whether to offer disk encryption pin setup.
# forced       Whether to requrie a disk encryption pin.
# min_length   Minimal encryption pin length.
# confirmation Require pin to be entered a second time.
#
# Default: offered: yes, forced: no, min_length: 1, confirmation: no
disk_encryption:
  offered: yes
  forced: no
  min_length: 0
  confirmation: yes

# User setup requests a printable name and a password by default.
#
# request_username      Request a username. Otherwise generated from name.
# provide_autologin     Whether to present an autologin option.
# min_password_length   Minimal password length.
# password_confirmation Require password to be entered a second time.
#
# Default: request_username: no, provide_autologin: no, min_password_length: 1, password_confirmation: no
user:
  request_username: no
  provide_autologin: True
  min_password_length: 1
  password_confirmation: yes


# gnome-initial-setup can handle user and locale setup.
# These settings allow to disable these pages.
#
# Default: skip_user: no, skip_locale: no

skip_user: yes
skip_locale: yes

failure_help_url: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'

browser_cmd: 'firefox'
disks_cmd: 'gnome-disks'
wifi_cmd: 'gnome-control-center wifi'
