%YAML 1.2
---

distribution_name: 'Shani OS'

# Default: None
scripts:
  prepare: /etc/os-installer/scripts/prepare.sh
  install: /etc/os-installer/scripts/install.sh
  configure: /etc/os-installer/scripts/configure.sh


# Configure whether an internet connection is required. Optionally set what
# URL/IP address is used to check for an existing internet connection.
#
# Default: connection_required: yes, checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'
internet:
  connection_required: no
  checker_url: 'http://nmcheck.gnome.org/check_network_status.txt'


fixed_language: en

welcome_page:
    logo: '/usr/share/pixmaps/shanios-logo.png'
    text: |
      Welcome to Shani OS!

      An Immutable OS for Ultimate Reliability

      This installer will guide you through a quick and secure setup.

      Let's begin!
    usage: yes

# Disk requirements for installation
#
# partition_ok  Whether partitions are accepted as installation targets
#                (Otherwise only complete disks can be used)
# min_size       Minimum size needed for installation (in Gigabyte)
#
# Default: partition_ok: no, min_size: 5
disk:
  partition_ok: no
  min_size: 64


# Disk encryption PIN setup.
#
# offered      Whether to offer disk encryption pin setup.
# forced       Whether to requrie a disk encryption pin.
# min_length   Minimal encryption pin length.
# confirmation Require pin to be entered a second time.
#
# Default: offered: yes, forced: no, min_length: 1, confirmation: no
disk_encryption:
  offered: yes
  forced: no
  min_length: 0
  confirmation: no

# User setup requests a printable name and a password by default.
#
# request_username      Request a username. Otherwise generated from name.
# provide_autologin     Whether to present an autologin option.
# min_password_length   Minimal password length.
# password_confirmation Require password to be entered a second time.
#
# Default: request_username: no, provide_autologin: no, min_password_length: 1, password_confirmation: no
user:
  request_username: no
  provide_autologin: True
  min_password_length: 1
  password_confirmation: yes


# gnome-initial-setup can handle user and locale setup.
# These settings allow to disable these pages.
#
# Default: skip_user: no, skip_locale: no

skip_user: yes
skip_locale: yes

failure_help_url: 'https://duckduckgo.com/?q="os-installer {}"+"failed installation"'

# Certain parts of the installer launch external programs. These can be configured here.
# Note: For calling the command, the string is split up by spaces.
#
# The browser_cmd will be called followed by a url.
#
# Default: browser: 'epiphany', disks: 'gnome-disks', reboot: 'reboot', wifi: 'gnome-control-center wifi'
commands:
  browser: 'firefox'
  disks  : 'gnome-disks'
  reboot : 'sudo poweroff'
  wifi   : 'gnome-control-center wifi'
